package org.example.controllers;

import org.example.domain.User;
import org.example.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class GreetingController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/")
    public String greeting(Model model) {
        return "greeting";
    }

    @GetMapping("/add")
    public String addUser(){
        return "add";
    }
    @PostMapping("/add")
    public @ResponseBody String addUser(@RequestParam(name = "username") String name, @RequestParam(name = "password") String password, Model model ){
        User user = new User();
        user.setUsername(name);
        user.setPassword(password);
        userRepository.save(user);
        return "Saved";
    }

    @GetMapping("/main")
    public Model main(Model model){
        Iterable<User> users = userRepository.findAll();
        model.addAttribute("users", users);
        model.addAttribute("Status", "TRUE");
        return model;
    }
}
